library(readr)
library(dplyr)

printf <- function(...) {
    invisible(print(sprintf(...)))
}

# The current working directory needs to be the 'UCI HAR Dataset'
# directory containing the extracted files from:
#
#   https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

stopifnot(file.exists('features.txt'))
stopifnot(file.exists('activity_labels.txt'))

# Read features.txt to get the names for the data columns. We use
# read.table rather than read_table because read.table separates by
# arbitrary whitespace and read_table assumes fixed-width columns.
readFeatures <- function() {
    featuresTable <- read.table(
        'features.txt', header = FALSE,
        col.names = c('FeatureId', 'FeatureName'),
        colClasses = c('integer', 'character'))

    # Return a vector of feature names.
    featuresTable$FeatureName
}

# Read activity_labels.txt to get the activity names.
readActivities <- function() {
    activityTable <- read.table(
        'activity_labels.txt', header = FALSE,
        col.names = c('FeatureId', 'FeatureName'),
        colClasses = c('integer', 'character'))

    activityTable
}

# Given a character vector of 'V1' ... 'Vxxx', extract the numeric
# portion and use that to subset the featureNames character vector.
convertColumnNames <- function(colNames, featureNames) {
    # Extract the numeric portion of the column name.
    colIndices <- gsub('V([0-9]+)', '\\1', colNames)
    # Convert to numeric.
    colIndices <- as.numeric(colIndices)
    # Subset the feature names with the indices from the column names.
    featureNames[colIndices]
}

# Given directory = 'foo' and base = 'bar', return 'foo/base_foo.txt'.
makeDatasetPath <- function(directory, base) {
    paste(directory, paste(base, '_', directory, '.txt', sep = ''), sep = '/')
}

# Read the measurement values for a dataset. We extract only the mean
# and standard deviation measurements, and rename the columns using
# their canonical feature names.
readMeasurements <- function(path, featureNames) {

    # Read the data values. Don't bother naming the columns yet since
    # they have duplicate names that will get us into trouble. Below
    # we will depend on the column names generated by read.table().
    dataValues <- read.table(path, header = FALSE)

    # The features contain measurements named -mean() and meanFreq().
    # From the code book, meanFreq() is "Weighted average of the
    # frequency components to obtain a mean frequency" and mean() is
    # "mean value". We are asked for the mean of a measurement, which
    # strongly implies the latter, so we only take feature names with
    # 'mean()'
    meanCols <- grep('mean\\(\\)', featureNames)
    stdCols <- grep('std\\(\\)', featureNames)

    # Collect just the columns with matching 'mean' or 'std' feature
    # names, so at this point we have just those measurements.
    dataValues <- bind_cols(dataValues[,meanCols], dataValues[,stdCols])

    # The columns of the measurements dataset are called V1 ... Vnnn. Extract
    # the numeric portion so that we can index back into the feature names.
    # Fortunately, at this point there are no duplicate feature names.
    names(dataValues) <- convertColumnNames(names(dataValues), featureNames)

    # Return the values.
    tbl_df(dataValues)
}

# Read a UCI dataset from the given directory.
readDataset <- function(directory, featureNames) {
    # Path to the sample values.
    measurementPath <- makeDatasetPath(directory, 'X')
    # Path to the activities for each sample.
    activityPath <- makeDatasetPath(directory, 'y')
    # Path to the subject for each sample.
    subjectPath <- makeDatasetPath(directory, 'subject')

    measurementValues <- readMeasurements(
        measurementPath, featureNames)

    activityValues <- read.table(
        activityPath, header = FALSE, col.names = c('ActivityId'))

    subjectValues <- read.table(
        subjectPath, header = FALSE, col.names = c('SubjectId'), colClasses = c('integer'))

    # Bind the activities and the subject IDs into the table,
    # returning a dplyr data frame tbl.
    tbl_df(bind_cols(measurementValues, activityValues, subjectValues))
}

# Read the activity metadata.
uci.meta.activity <- readActivities()
# Read the features metadata.
uci.meta.features <- readFeatures()

# Read the test and train datasets.
uci.dataset.test <- readDataset('test', uci.meta.features)
uci.dataset.train <- readDataset('train', uci.meta.features)

# Concat the test and training observations.
uci.dataset.combined <- bind_rows(uci.dataset.test, uci.dataset.train)
